name: Backport

on:
  # allows to manually run the job at any time, also for webhooks
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.1
        with:
          global: true
          name: ${{ vars.GIT_NAME }}
          email: ${{ secrets.GIT_EMAIL }}
          actor: ${{ github.repository_owner }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: run
        run: deno run --allow-net --allow-env --allow-run src/mod.ts
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GITEA_FORK: ${{ github.repository_owner }}/gitea