name: Denopendabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Update
        uses: hasundue/denopendabot@0.15.0 # @denopendabot hasundue/denopendabot
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          working-branch: denopendabot
          labels: dependencies