name: Main

on:
  # run automatically every 30 minutes
  schedule:
    - cron: '*/30 * * * *'
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main
    - deploy

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - name: run
        uses: oleksiyrudenko/gha-git-credentials@v2.1.1
        with:
          global: true
          name: ${{ variables.GIT_NAME }}
          email: ${{ secrets.GIT_EMAIL }}
          actor: ${{ github.repository_owner }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          # print configured git user and email
          git config --global user.name
          git config --global user.email
          # deno run --allow-net --allow-env src/mod.ts
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GITEA_FORK: ${{ github.repository_owner }}/gitea