name: Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Update dependencies
        run: deno run -A https://deno.land/x/udd/main.ts src/**.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update dependencies
          title: Update dependencies
          body: >
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).
          branch: deno-dependency-updates
          labels: dependencies